### ISSUE TITLE
Contribute?

### ISSUE THREAD

**Issue by jagmann1** [BenediktBergmann/PCF-Controls#1]
Hi, can we contribute to this PCF control by translate the solution to Norwegian and add validation for Norwegian SSN?

**Comment by BenediktBergmann** [comment]
Sure. I will add you as a collaborator.

**Comment by BenediktBergmann** [comment]
I just checked regarding the structure of the norwegian ssn.
It is similar but a bit different to the Swedish one.
I am not sure whether it would be better to create a separate Control for the Norwegian SSN or adding it to this one. Both have ups and downs.

**Comment by jagmann1** [comment]
We have a use scenario that both norwegian and swedish (and later maybe finnish) persons are in the same instance of Dynamics, so therefore I though have multiple SSN validations (as configuration of the PCF Control) could be a good solution. What do You think are the disadvantage of that?

**Comment by BenediktBergmann** [comment]
Yeah i thought about the same thing. Maybe we can show a small flagg beside the number when we have identified for which country it is.

The downside could be that we in our projects for example only need Swedish SSN and our integrations will not work with a norwegian one. A solution could be that we add the possibility to configure whether to allow SSNs for different countries.

I will add this to the list of features in the readme
