### ISSUE TITLE
HTML formatting of text 

### ISSUE THREAD

**Issue by lowcodelewis** [BenediktBergmann/PCF-Controls#101]
Hi Benedikt.

Thank you for the fantastic control. This is not an issue report but a 'nice to have' / requirement which would be great as part of the conversation control PCF if you get around to adding some new stuff in.

Currently I don't believe it is possible to use HTML tags in the text messages shown using the control.

It would be great if the PCF could support HTML tags and rich text to make it possible to display hyperlinked text within messages. 

Currently I am using the control and when supplying records through a subgrid that contain messages with HTML <a> tags for links, these get displayed as plain text, obviously as expected due to the limitation.

If this showed the links as rich text hyperlinks, that would be fantastic! 

Thank you so much in advance if you manage to get around to this

Best,
Lewis

**Comment by BenediktBergmann** [comment]
This is implemented and released in version 2.2.1.0
