### ISSUE TITLE
CheckPhoneNumberControl: Unable to clear field value

### ISSUE THREAD

**Issue by LarsBauer** [BenediktBergmann/PCF-Controls#13]
Hej,

I am struggling to clear the field value when using the CheckPhoneNumberControl.  Once a valid phone number is saved I am not able to clear the field. On the form UI the field value gets set to `---` but the field won't get marked as changed so I am unable to save the form. When I re-open the record the old phone number is still there.

I tried debugging the component and could narrow down the problem to the `inputOnChange` method. When the field value is an empty string the value won't be returned. 
```typescript
if(parsedPhoneNumber === undefined || !parsedPhoneNumber.isValid()){
   this.handleValue(this._inputElement.value);
   this._numberValidReturnValue = false;
}
```

I am not sure whether this behavior is intentional. It seems logical because it is no valid phone number but I would exclude empty strings from this check to allow the clearance of phone number fields.

Thanks in advance!

**Comment by BenediktBergmann** [comment]
This should be fixed in the new version (1.9.0.0) I just released.
Please let me know if the issue still exists or if you find any other issue.
