### ISSUE TITLE
Sets an undifined value if format is correct

### ISSUE THREAD

**Issue by CnytSntrk** [BenediktBergmann/PCF-Controls#2]
We checked with the different Country codes. It detecting the incorrect format but if the format is correct sets as a "undifined" to field. Example Code: TR,ES.

**Comment by BenediktBergmann** [comment]
I noticed the problem two days ago. It is working in the PCF harnesh but not in a CDS App.

I will take a look at it as soon as possible.

**Comment by BenediktBergmann** [comment]
Now this issue is fixed. Please try the new release.
