### ISSUE TITLE
Validation error on load

### ISSUE THREAD

**Issue by falstaffjobs** [BenediktBergmann/PCF-Controls#34]
Hi Benedikt,

we're experiencing validation errors every time I open a contact:
![Bildschirmfoto 2020-12-03 um 22 42 54](https://user-images.githubusercontent.com/10829964/101016783-566ce400-35bd-11eb-97b4-d8170ce0394e.png)

as soon as i copy and paste the number again there is no error - but it seems on load it doesn't work properly. is that a known issue?

**Comment by BenediktBergmann** [comment]
Thanks for reporting this. I will take a look at it.

**Comment by WhiteyC** [comment]
Even with the latest version, @falstaffjobs issue is still a problem.
If you log off CRM, restart the browser, log back in again, the issue persists until you perform a forced refresh.
I can confirm the number is valid but shows as incorrect.
There must still be a caching issue.

**Comment by BenediktBergmann** [comment]
I am not able to reproduce the problem.
Which configurations do you have on the field?
What are the exact steps to reproduce the error?

**Comment by falstaffjobs** [comment]
It's been a while, sorry. I have had another look at it - it seems to only occur in google chrome (latest), it doesn't show a validation error in firefox. 

bug description: Every time I open a contact with a (valid) mobile phone number I get the error on load. It seems I can get rid of it by cutting the number and pasting it in the field again - than the validation error is gone, even after i reload the page

the configuration is the following:
![Bildschirmfoto 2021-01-19 um 01 38 40](https://user-images.githubusercontent.com/10829964/104928771-28b9ee00-59f7-11eb-9c62-a6ec508860da.png)
![Bildschirmfoto 2021-01-19 um 01 38 30](https://user-images.githubusercontent.com/10829964/104928774-2a83b180-59f7-11eb-8ec8-325f903978c7.png)

any chance we can get this fixed?

**Comment by BenediktBergmann** [comment]
Thanks for your response and the error details. I will take another look at it.

**Comment by BenediktBergmann** [comment]
I am very sorry for the very late response.
I now tried to reproduce your error with the exact same configuration. Unfortunately, I don't get the error. Which version do you use?

**Comment by BenediktBergmann** [comment]
Closed because of inactivity for 6 months.
