### ISSUE TITLE
Use Custom Provider - Click to Call

### ISSUE THREAD

**Issue by BenjaminChesnel** [BenediktBergmann/PCF-Controls#35]
Hello,

I'm trying to do same as the "Channel Communication Control" which call the Channel Provider i configured in "Channel Integration Framework" but it's not working.

Maybe i'm not doing the configuration well ?

I tryied several things : use different click to call provider (tel, teams or custo) it doesn't work.

I thought i just needed to select "custom" and add the label/name of my channel provider in the parameter "Custom click to call provider" but it doesn't work too (it open a new tab with the name of the provider i put + phone number)

Does the issue is in the PCF ? I'm using V1.9.4.0.

Thanks for your help.

Best Regards,

Benjamin.

**Comment by BenediktBergmann** [comment]
Sorry for my very late response. I haven't seen your issue earlier.
Could you provide the exact configuration (including screenshots)?

As you mention the PCF will open a new tab with the custom provider + ":" + phone number, depending on which app is configured on your machine for the certain provider it should open this application. This means it depends on your local configuration as well.
I read something a while ago that Chrome might have blocked it. Which browser do you use?

Does it work with the standard call button?

**Comment by BenediktBergmann** [comment]
Closed because of inactivity for 6 months.
