### ISSUE TITLE
prevent being saved?

### ISSUE THREAD

**Issue by paulstegmann** [BenediktBergmann/PCF-Controls#50]
Hi!

is it possible to configure the pcf in such a way that, in addition to the warning message, the dataset cannot be saved in the first place?

Best
Paul

**Comment by BenediktBergmann** [comment]
Hi Paul,
This should be possible yes.
You will need an additional field which will be set. If it is false the form should be configured in a way that it isn't possible to save.

Please see one of my blog posts for that

https://benediktbergmann.eu/2020/05/01/pcf-prevent-saving-the-form-when-input-is-invalid/#configure_cds_mda

//Benedikt

**Comment by paulstegmann** [comment]
Hi Benedikt,

thx for the quick response! Your provided solution works fine. One little thing: Is it possible to hide the default error label? Now we get two ones on the field:
https://drive.google.com/file/d/1suDwjrhGOfUunF9fplxSBK9m1iKf8d_I/view?usp=sharing

Thx
Paul

**Comment by BenediktBergmann** [comment]
Sorry for the late response.
It should be only one error. I have to check it.

**Comment by BenediktBergmann** [comment]
I just tested it in my development environment. I only see one error message.
Could you provide your exact configuration?

**Comment by BenediktBergmann** [comment]
Closed because of inactivity for 6 months.
