### ISSUE TITLE
Can't specify related entity or activity view when using "UseSubgridData" set to "No"

### ISSUE THREAD

**Issue by hew2702** [BenediktBergmann/PCF-Controls#61]
When not using the subgrid data on a third table, I can choose the activity table to display but there's not an option to choose which lookup field on the third table to use for the related activity records nor is there a way to specify the custom conversation view to use for the selected activity table.

**Comment by BenediktBergmann** [comment]
I have fixed this issue in the new release (2.1.5.0)
