### ISSUE TITLE
The Input field is clear out Issue (Check Phone Number Control)

### ISSUE THREAD

**Issue by SatkunamSuganthar** [BenediktBergmann/PCF-Controls#62]
Hi Ben, We are using this control for mobile no validation from our instance of CRM. 

Sometime user reports that mobile no (Input filed is empty) but when I query in the back end, the value exists. When they do the page on load, the input field number appear. Onething,I noticed that, Form shows that record is 'Unsaved'. user does not want to save as it could save the null value in backend rather user load the page to get the number reappear and save. 

it is hard to replicate the issue as it does not happen often and i could not even debug as the page loads, the value appear back. 

we were using 1.9 version. 

My question, does any of the user reported the issue whether the Input field clear out when onloads ?

I have updated the version to latest 2.1 and see whether user is reporting an issue

**Comment by SatkunamSuganthar** [comment]
@BenediktBergmann  much appreciated if you could respond to my below question

My question, does any of the user reported the issue whether the Input field clear out when onloads ?

**Comment by BenediktBergmann** [comment]
Thanks for opening an issue for that.

When I remember correctly I had a similar error earlier. I can't remember in which version I fixed it, but it could have been from version 1.9 to 2.1. So please let me know if this is not helping.

In the meantime: Could you provide me with the exact configuration you are using?

**Comment by SatkunamSuganthar** [comment]
Apologies for the delay in reply. Please see the screenshot of the configuration of the control.

![image](https://user-images.githubusercontent.com/97066265/152679088-adb1d9af-5b3d-4d7e-9911-cd233ea9248c.png)

![image](https://user-images.githubusercontent.com/97066265/152679108-63aa6e59-8b0a-4020-8a1e-1f8ae4a03afa.png)

![image](https://user-images.githubusercontent.com/97066265/152679117-d5f50d14-cbeb-496a-af5c-5c2b53990702.png)

**Comment by SatkunamSuganthar** [comment]
Hi @BenediktBergmann Seems like this issue is no longer happening. Thanks for the fix
