### ISSUE TITLE
Incorrect Phone number False Positive Error

### ISSUE THREAD

**Issue by SatkunamSuganthar** [BenediktBergmann/PCF-Controls#63]
Hi @BenediktBergmann I have another issue appeared after the upgrade of the PCF control. Even though the number is correct, it is showing as a incorrect number. 

![image](https://user-images.githubusercontent.com/97066265/154880817-6a451e36-7ec8-430e-8076-9d692f46ed38.png)

To solve this/workaround it, we have to remove +61 (extension) and re-add, the error disappear. 

Do you have any fix for this issue

**Comment by SatkunamSuganthar** [comment]
The version of the control is 2.1.5.0

![image](https://user-images.githubusercontent.com/97066265/154882445-57c42908-ddfd-4f78-89a3-cc1ef014ab8e.png)

![image](https://user-images.githubusercontent.com/97066265/154882463-55a809e0-f08f-4dc2-aed5-31d91d6b15e9.png)

![image](https://user-images.githubusercontent.com/97066265/154882484-38336c88-12ee-4189-b782-91f43d3393fa.png)

**Comment by BenediktBergmann** [comment]
@SatkunamSuganthar unfortunately I was not able to reproduce the problem. Have you found any consistency in experiencing this error? What are the exact steps to take to reproduce it?

**Comment by FabienV-FR** [comment]
I have the same issue on the 2.1.5.0 without any default country code or Allowed country codes.
It happens when I update phone data by excel online import or even with business rules

The message disappears after saving

**Comment by FabienV-FR** [comment]
If the phone is displayed in a column the view preceding the form then no false positive are displayed

**Comment by BenediktBergmann** [comment]
Thanks for the additional information. I will take a look at it later today.

**Comment by BenediktBergmann** [comment]
I am very sorry for the very late reply.

Do you still have the problem @SatkunamSuganthar & @FabienV-FR?

I am currently not able to reproduce the error.
If you still have it: Could you record a short video showing how to reproduce the error?

**Comment by BenediktBergmann** [comment]
Close because of no reply.

Please feel free to reopen when the error still exists.
