### ISSUE TITLE
Phone Number Control gets cleared 

### ISSUE THREAD

**Issue by Philschke** [BenediktBergmann/PCF-Controls#75]
Hi Benedikt,

thank you for you great work.
Our Microsoft Dynamics CRM 365 Users found a behavior that clears the phone number field, even if it is persisted in the specific account, when they opens a form on the entity (account) the first time. I tried a lot to reproduce the issue, but in the end it was simple. I will explain the issue below.

## Phone Number control gets **cleared** when the field for the telephone number is not present in view
 1. Open a View in the account entity which does not include the phone number field
 ![image](https://user-images.githubusercontent.com/43903945/195317079-8b981e3e-4b6f-44e8-9e76-8b89aa822347.png)

 2. Open a record. The Form will be applied. The custom control is on the field "Telefon". And as you can see the phone control is empty. This leads our users to retype the telephone field. They don´t know, that there is a value in the background.
 ![image](https://user-images.githubusercontent.com/43903945/195319070-0ca5f54c-bb57-44f8-a033-4efe80afa2f6.png)

3. When I go back now to the view and reopen the same account the telephone field will not be cleared as you can see in the screenshot. To recall the error you have to do a cache refresh in the view and then open the account form once again.
![image](https://user-images.githubusercontent.com/43903945/195319595-790cb089-aa91-49c7-a1f0-45ba1d279eea.png)

## Phone Number control gets **not cleared** when the field for the telephone number is present in view
When I do the steps again with a view that contains the telephone field, the telephone number will not be cleared from the custom control.
1.
 ![image](https://user-images.githubusercontent.com/43903945/195320281-cec9c5d3-324b-49bf-9a5e-6b5520155641.png)
2.
 ![image](https://user-images.githubusercontent.com/43903945/195320537-642badc7-7d2e-4a58-bbb5-816d09178c17.png)

We are using the version 2.1.5.0.

Can you help us with our strange problem?

Thank you in advance.
Philipp.

**Comment by TobiasCloes** [comment]
We have identified the same problem

**Comment by BenediktBergmann** [comment]
Thanks for reporting this issue. I will take a look at it later today.

**Comment by BenediktBergmann** [comment]
I was able to reproduce the error. My current problem is that I only can do this once a day. Cleaning my cache doesn't bring back the error. Has any of you had luck in reproducing it more often?

**Comment by Philschke** [comment]
Hi Benedikt,
your last answer was a while ago. I wanted to ask friendly if you could still find out something or if I can help you solve the problem? There is still no improvement of the problem at our company.
Thank you.

**Comment by BenediktBergmann** [comment]
I am very sorry for the very late reply and delay, @Philschke. I will take another look at it.

**Comment by BenediktBergmann** [comment]
I just retried with several browsers as well as with clearing the cache (as described in the link you provided). Unfortunately, I can't reproduce the error at all at the moment.

Would you be able to record a short video showing how you reproduce the problem? Or if that would be better/easier for you we could plan in a short meeting regarding this.

**Comment by BenediktBergmann** [comment]
Close because of no reply.

Please feel free to reopen when the error still exists.

**Comment by Philschke** [comment]
Hi Benedikt.
I´m so sorry for the late response. I have not received any notification about your comments. The issue still persist. But I cant reproduce this "on demand".
Every morning I have got this issue once in all our dynamics environments (we have got three).
Maybe we can come together for a talk?

By the way: I have debugged your code and in the first execution (where the error occurs) the raw value from the value field is _null_. Maybe this can help us as information. Please see screenshot below.
![debug_screenshot1](https://github.com/BenediktBergmann/PCF-Controls/assets/43903945/87ffbc67-c5b4-4da1-a79b-0d04ed1296a3)
