### ISSUE TITLE
New Feature - Filter by Phone Number Used

### ISSUE THREAD

**Issue by hew2702** [BenediktBergmann/PCF-Controls#95]
Please add the ability to filter the SMS records based on which phone number was used by the User. For example, if on a contact record there is a field called "User Numbers" which lists all of the mobile numbers that a business uses in the CRM to communicate with contacts. Based on the choice in this field, the control would filter for only SMS records with a matching custom "Business Number"/"CRM Number" field. That way when having multiple conversations with one contact the texts related to particular business numbers can remain separate and the conversations don't get mixed together within the control.

**Comment by BenediktBergmann** [comment]
I don't think I understand what you would like to have.
Could you elaborate on this a bit more?

When I understood you correctly you would have a field on contact containing the number and a field on your message entity containing the number where the message came from. If those two match the message should be shown. Correct?

Spontaneously this reads like a very specific/edge-case scenario.

**Comment by hew2702** [comment]
Yes, that's exactly correct. Filter for related activity records where X field on activity record equals X field on the contact record.
![image](https://github.com/BenediktBergmann/PCF-Controls/assets/59235984/60dac871-dcfb-4cc7-af22-be28f269ffc5)
![image](https://github.com/BenediktBergmann/PCF-Controls/assets/59235984/6f583ed3-0b99-4eed-a780-41de7155db06)

I agree this could seem like an edge-case, but it could be customized for other fields like if the current user equals the sender/recipient/regarding user on the related activity.

**Comment by BenediktBergmann** [comment]
Perfect. Thanks for the additional information. I will investigate this.

**Comment by BenediktBergmann** [comment]
While looking into this I came across another question.
This should only filter the customers messages?
If we filter the messages send by the customer only it could generate weird scenarios where there are messages from us in the conversation which are from another conversation.
But if we filter both we would have to write the correct number to both outbound and inbound messages.
Any suggestions?

**Comment by BenediktBergmann** [comment]
I implemented a first version of this feature.
There are 2 new fields. One to specify the column to compare with on the message (Filter Column) and one to specify the value to compare with (Filter Value). The idea is to bind the value to a field on the table where the subgrid is shown.

This will be included in the next release as well (as #94).

**Comment by BenediktBergmann** [comment]
New version (2.2.0.0) was just released.
