### ISSUE TITLE
PCF seems not working with Aruba (country) +297

### ISSUE THREAD

**Issue by bruceborgna** [BenediktBergmann/PCF-Controls#96]
Hello, thx for your great PCF, we notice that it semms to no working with Aruba country + 297, not able to obtain correct number. Thx for your help.

**Comment by bruceborgna** [comment]
https://en.wikipedia.org/wiki/Telephone_numbers_in_Aruba

Thx for your help !

**Comment by BenediktBergmann** [comment]
I just tested it and It worked as expected for me. Have you configured the CountryCode of Aruba (AW) as an accepted CountryCode?

**Comment by BenediktBergmann** [comment]
Close because of no reply.

Please feel free to reopen when the error still exists.
