### ISSUE TITLE
Setting "Use subgrid data " to No and providing "Entity name" of my activity entity for which earlier I was using subgrid data, stops displaying the data

### ISSUE THREAD

**Issue by Komal024** [BenediktBergmann/PCF-Controls#98]
I have been using one of my activity entity subgrids embedded into a section in a form and embedded with the Conversation control to display my conversation records. It works fine when I set "Use Subgrid data" to "Yes". But when I set "Use subgrid data" to "No" and in "entityName" I provided logical name of my entity in SingleLine.text parameter. On doing these changes the records itself stopped displaying.

**Comment by Komal024** [comment]
Hi, following up on this issue, in case there is an update or if there are any steps or information required from my side.

**Comment by BenediktBergmann** [comment]
Hej @Komal024,
The intent of the "Use Subgrid data" configuration is to have the conversation on the message itself.
Let's say you have a custom activity which is related to a Case. You show the conversation on the Case using the data of a subgrid. Then you also want to show the same conversation when viewing a message. Here you can't use the subgrid, therefore I created the "Use Subgrid data" configuration. This only works on the underlying table though. This will not work on Case (in our example).
I have described it a bit more here:
https://benediktbergmann.eu/2020/05/23/pcf-use-conversationcontrol/#advanced_configuration

In our conversation on LinkedIn you mentioned some issue with when you have more than 25 rows. Is this still the case?

**Comment by Komal024** [comment]
Hi @BenediktBergmann , My requirement is that I want to load all of my messages at once and do not want to have "Load More" button. Currently it loads only 25 messages at a time and I have to keep clicking on Load More for further messages. Is there a way to achieve this?
On LinkedIn you mentioned that if I set "Use subgrid data" to "No" and in "entityName" provide logical name of my entity in SingleLine.text parameter then it should not show "Load More" which did not work for me.

**Comment by BenediktBergmann** [comment]
Hej @Komal024,
I just rechecked. For me it shows even more than 25 rows.
Could you send me screenshots of your configuration? Both of the PCF as well as of the Subgrid?
Do all your rows in the subgrid have values in the description? If the Description is empty the rows won't be shown in the PCF.

**Comment by Komal024** [comment]
Hi @BenediktBergmann ,

It shows more than 25 rows for me as well but I have to click on "Load More" button to load more than 25 rows. So I want all messages to load at once and I do not want to use "Load More".
Yes all my rows in subgrid have values in description. 

For some reason it is not allowing me to attach screenshots , so below are my configurations for PCF:

Dataset: (this is my subgrid, cannot share the name)
Text column: description(SingleLine.Text)
Sender column: test_sender (SingleLine.Text)
Customer identifier: 100000000 (SingleLine.Text)
Show scrollbar: Yes (Enum)
Open strategy: Centered Modal (Enum)
Modal width: 50 (Whole.None)
Show empty messages: No (Enum)
Use Subgrid data: Yes (Enum)
Sorting order: ASC(enum)

**Comment by BenediktBergmann** [comment]
For me it does not show the Load More button. It just shows more than 25 messages.
So I do assume it is some kind of configuration miss match between your setup and mine.
We "just" have to find what configuration it is.

Best would be how the subgrid is configured in terms of used rows and so on. But also the used view.

**Comment by Komal024** [comment]
It is a system view and One Column and Row Layout -->Number of rows configuration is 4. I have tried increasing this number. It does not help.

**Comment by BenediktBergmann** [comment]
Hej @Komal024,
I played around with different configurations of the subgrid. The only way for me to reproduce the behaviour you are describing was to set the field "Maximum number of rows" to 10. With that the PCF shows a "Load More" button. When I set it to 250 it will show all my messages without the "Load more" button.
Could you retry setting the number to something higher and reload the page (including deleting the cache)?

What happens when you add the exact same subgrid but without the PCF. Do you get all the rows?

**Comment by Komal024** [comment]
Hi @BenediktBergmann , I am opening that chat from case timeline where it is linked as an activity and it is opening as Omnichannel Application tab templates. Increasing numbers of rows to 250 for subgrid did not help, it still showed Load more . If I add exact same subgrid without PCF, it lists all 50 records on first page as 1-50 of 50 though I have to use scroll bar with the list to see all records.

**Comment by BenediktBergmann** [comment]
@Komal024 Could you attach screenshots of your configuration to this issue?

**Comment by Komal024** [comment]
@BenediktBergmann Apologies but It is not allowing me to attach, not sure but could be because of my org policy or something. If there is someplace else like some email where I can share you those screenshots of subgrid and PCF control configurations.

**Comment by BenediktBergmann** [comment]
@Komal024: sorry for not responding for so long.
I assume you still have the problem, correct?

**Comment by Komal024** [comment]
Hi Benedikt,

Thanks for your email. Actually i have left the organisation for which i
was working earlier who used this control. So i do not have access to the
system anymore.

Thanks
Komal

**Comment by BenediktBergmann** [comment]
Thanks for the response.
I will close the issue.
